// AUTO-GENERATED by RuleC compiler. Do not edit by hand.
#include "evaluate_rules.h"

void evaluate_rules(const SensorState *s) {
    // RULE: overheat_alert
    if (((s->temp > 30.0) && (s->humidity < 20.0))) {
        action_alert("High temp, low humidity");
    }

    // RULE: comfort_zone
    if (((s->temp >= 18.0) && (s->temp <= 26.0))) {
        action_log("Temperature within comfort range");
    }

    // RULE: intruder_check
    if (((s->motion == 1) && (!(s->temp > 40.0)))) {
        action_actuate("light", "ON");
    }

}
