// AUTO-GENERATED by RuleC compiler. Do not edit by hand.
#ifndef EVALUATE_RULES_H
#define EVALUATE_RULES_H

typedef struct {
    float temp;
    float humidity;
    int motion;
} SensorState;

// Action callbacks — implement these in your application/harness.
void action_alert(const char *message);
void action_log(const char *message);
void action_actuate(const char *device, const char *state);

// Evaluates every compiled rule against the current sensor readings.
void evaluate_rules(const SensorState *s);

#endif // EVALUATE_RULES_H
